#!/bin/bash
set -euxo pipefail
# shellcheck disable=SC2046
curl --fail --remote-name-all --remote-time \
    $(awk -F '[ ()]' '/^SHA512 \(/ {
        printf "https://thar-upstream-lookaside-cache.s3.us-west-2.amazonaws.com/%s/%s/%s\n", $3, $6, $3
    }' "$1")
