#!/usr/bin/env bash

# wrapper script to run a specific major release of Go

set -eu -o pipefail
shopt -qs failglob

# prefer GO_VERSION over GO_MAJOR if present, to preserve original behavior
if [ -n "${GO_VERSION:-}" ] ; then
  GO_MAJOR="${GO_VERSION%.*}"
fi

exec /usr/libexec/go-"${GO_MAJOR}"/bin/go "${@}"
