#!/usr/bin/env bash

# wrapper script to run the latest included release of Go

set -eu -o pipefail
shopt -qs failglob

LATEST_GO=$(find /usr/libexec/ -type d -regex '.*/go-1\.[0-9]+$' -printf '%f\n' | sort -V | tail -n 1)

if [ -z "${LATEST_GO}" ]; then
  echo "Error: No Go installation found in /usr/libexec/" >&2
  exit 1
fi

# prefer the musl flavor if GOLIBC indicates that we should
if [ "${GOLIBC:-}" = "musl" ] ; then
  LATEST_GO+="-musl"
fi

exec /usr/libexec/"${LATEST_GO}"/bin/go "${@}"
