[licenses]

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "MIT",
    # "OpenSSL",
    "Unlicense",
    "Zlib",
]

exceptions = [
    { name = "webpki-roots", allow = ["MPL-2.0"] },
    { name = "target-lexicon", allow = ["Apache-2.0 WITH LLVM-exception"] },
    { name = "unicode-ident", allow = ["MIT", "Apache-2.0", "Unicode-3.0"] },
    { name = "icu_collections", allow = ["Unicode-3.0"] },
    { name = "icu_locale_core", allow = ["Unicode-3.0"] },
    { name = "icu_normalizer", allow = ["Unicode-3.0"] },
    { name = "icu_normalizer_data", allow = ["Unicode-3.0"] },
    { name = "icu_properties", allow = ["Unicode-3.0"] },
    { name = "icu_properties_data", allow = ["Unicode-3.0"] },
    { name = "icu_provider", allow = ["Unicode-3.0"] },
    { name = "litemap", allow = ["Unicode-3.0"] },
    { name = "potential_utf", allow = ["Unicode-3.0"] },
    { name = "tinystr", allow = ["Unicode-3.0"] },
    { name = "writeable", allow = ["Unicode-3.0"] },
    { name = "yoke", allow = ["Unicode-3.0"] },
    { name = "yoke-derive", allow = ["Unicode-3.0"] },
    { name = "zerofrom", allow = ["Unicode-3.0"] },
    { name = "zerofrom-derive", allow = ["Unicode-3.0"] },
    { name = "zerotrie", allow = ["Unicode-3.0"] },
    { name = "zerovec", allow = ["Unicode-3.0"] },
    { name = "zerovec-derive", allow = ["Unicode-3.0"] },
]

[bans]
# Deny multiple versions or wildcard dependencies.
multiple-versions = "deny"
wildcards = "deny"

skip = [
    # older version used by gix-actor
    # newer version used by toml_edit
    { name = "winnow", version = "0.6.26" },

    # older version from getrandom v0.2.15
    # newer version from getrandom v0.3.1
    { name = "wasi", version = "0.11.0+wasi-snapshot-preview1" },

    # older version from rustsec v0.30.1
    # newer version from gix v0.70.0
    { name = "thiserror", version = "1.0.69" },
    { name = "thiserror-impl", version = "1.0.69" },

    # older version from petgraph (via krates)
    # newer version from indexmap
    { name = "hashbrown", version = "0.15.5" },

    # older version from ring
    # newer version from tempfile
    { name = "getrandom", version = "0.2.15" },
]

skip-tree = [
    # windows-sys is not a direct dependency. we skip the
    # dependency tree because windows-sys has many sub-crates
    # that differ in major version.
    { name = "windows-sys" },
    # redox_syscall is also not a direct dependency.
    { name = "redox_syscall" },
    # core-foundation is not a direct dependency.
    { name = "core-foundation" },
]

[sources]
# Deny crates from unknown registries or git repositories.
unknown-registry = "deny"
unknown-git = "deny"
